[package]
name = "augustium-wasm"
description = "WebAssembly bindings for the Augustium programming language compiler"
version = "1.0.1"
authors = ["August Moreau <august@augustium.org>"]
license = "MIT"
repository = "https://github.com/AugustMoreau/augustium"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false